### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by synesta** [6eamed/timely-for-roblox#1]
`Line 4 of README.md` - "Does Timely inject ANYTHING into ROBLOX? No."
This is false, it injects multiple viruses and your PC will be #destroyed once you open the application.

**Comment by synesta** [comment]
Proof : 
![image](https://user-images.githubusercontent.com/72947065/123530525-4dfb0880-d6c9-11eb-9b57-32ac5936a425.png)

**Comment by 6eamed** [comment]
Hello! Please look through the source code if you are unsure about using Timely!

**Comment by synesta** [comment]
I asked for support with this virus... got rude answer in return. FUck you 
![image](https://user-images.githubusercontent.com/72947065/123530543-8dc1f000-d6c9-11eb-9516-0be4b3d3ecf3.png)
